name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # run build/lint first to catch errors early
    - name: Install dependencies
      run: npm ci
    - name: Build Typescript sources
      run: npm run build
    - name: Lint source
      run: npm run lint
    - name: Use JupyterLab
      run: python -m pip install --upgrade jupyterlab
    - name: Install extension
      run: jupyter labextension install . --no-build
    - name: Build extension
      run: jupyter lab build
