name: Build and Publish

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: quay.io/jupyter/r-notebook:lab-4.2.3

    steps:

    # build and upload to PyPI
    - name: Install twine
      run: python -m pip install build

    - name: Build the federated extension in a separated build environment
      run: |
        python -m build

    - name: Publish the Python package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        username: __token__
        password: ${{ secrets.PYPI_TOKEN }}
