name: Build and Publish

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'  # specify python version

    - name: Use Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: 22

    # build and upload to PyPI
    - name: Install twine
      run: python -m pip install build

    - name: Build the federated extension in a separated build environment
      run: |
        python -m build

    - name: Publish the Python package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        username: __token__
        password: ${{ secrets.PYPI_TOKEN }}
