name: Build and Publish

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # specify python version

    - name: Use Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: 20

    # run build/lint first to catch errors early
    - name: Install dependencies
      run: npm ci

    - name: Build Typescript sources
      run: npm run build

    - name: Lint source
      run: npm run lint

    - name: Use JupyterLab
      run: python -m pip install --upgrade jupyterlab

    - name: Install extension
      run: jupyter labextension install . --no-build

    - name: Build extension
      run: jupyter lab build

    # build and upload to PyPI
    - name: Install twine
      run: python -m pip install --upgrade twine setuptools wheel build

    - name: Build the federated extension in a separated build environment
      run: |
        python -m build

    - name: Publish the Python package
      uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.PYPI_TOKEN }}
